name: AI Agent Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for better context

      - name: Get Pull Request Details
        id: pr-details
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            return {
              title: pr.title,
              body: pr.body,
              base_branch: pr.base.ref,
              head_branch: pr.head.ref,
              changed_files: pr.changed_files,
              additions: pr.additions,
              deletions: pr.deletions
            };

      - name: Trigger n8n Workflow
        run: |
          curl -X POST ${{ secrets.N8N_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "pull_request": {
                "title": "${{ steps.pr-details.outputs.title }}",
                "body": "${{ steps.pr-details.outputs.body }}",
                "base_branch": "${{ steps.pr-details.outputs.base_branch }}",
                "head_branch": "${{ steps.pr-details.outputs.head_branch }}",
                "changed_files": ${{ steps.pr-details.outputs.changed_files }},
                "additions": ${{ steps.pr-details.outputs.additions }},
                "deletions": ${{ steps.pr-details.outputs.deletions }}
              },
              "repository": {
                "name": "${{ github.repository }}",
                "owner": "${{ github.repository_owner }}"
              },
              "sender": {
                "login": "${{ github.actor }}"
              }
            }'
